/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/elector` | `/elector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agrupaciones` | `/agrupaciones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agrupaciones/[id]` | `/agrupaciones/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/agrupaciones/candidato/[id]` | `/agrupaciones/candidato/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/elector` | `/elector`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agrupaciones` | `/agrupaciones`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agrupaciones/[id]` | `/agrupaciones/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/agrupaciones/candidato/[id]` | `/agrupaciones/candidato/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendario${`?${string}` | `#${string}` | ''}` | `/calendario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/elector${`?${string}` | `#${string}` | ''}` | `/elector${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agrupaciones${`?${string}` | `#${string}` | ''}` | `/agrupaciones${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/elector` | `/elector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agrupaciones` | `/agrupaciones`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/agrupaciones/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/agrupaciones/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agrupaciones/candidato/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/agrupaciones/candidato/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/agrupaciones/[id]` | `/agrupaciones/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/agrupaciones/candidato/[id]` | `/agrupaciones/candidato/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
